In [208]:
import pandas as pd

In [209]:
df1 = pd.read_csv(r"C:\Users\kevin\startuptalky_funding_2025.csv")
df1

,name,sector,city,state,funding_total,funding_round,number_of_investors,investors
0,Art Of Time,Consumer Goods > Retailers,Maharashtra,NaN,Undisclosed,Series B,1,Plutus Wealth Management
1,Sammaan Capital,Financial Services > Consumer and SME Loans,Delhi,NaN,$1B,Post IPO,2,"IHC, Marshall Wace"
2,Freight Tiger,Consumer > Logistics Tech,Maharashtra,NaN,$13.5M,Series C,2,"Tata Motors, Lightspeed India"
3,Recyclaro.com,Environment Tech > Solid Waste Management Tech,Uttar Pradesh,NaN,$1M,Seed,1,CapitalOven
4,GrowXCD,Financial Services > Consumer and SME Loans,Tamil Nadu,NaN,$22.5M,Series B,2,"Blue Earth Capital, Lok Capital"
...,...,...,...,...,...,...,...,...
743,Zoplar,Medical Equipment Procurement,Gurugram,NaN,$3.4 million,Series A,6,"Blume Ventures, Beenext, Saison Capital, Atriu..."
744,Moonrider,Electric Tractor Tech,Bengaluru,NaN,$2.2 million (Rs 19 crore),Seed Round,3,"AdvantEdge Founders, Micelio Technology Fund, ..."
745,Consint.AI,Healthtech,Noida,NaN,Rs 5 crore,Funding Round,2,"Equanimity Ventures, Seafund"
746,NapTapGo,Affordable Hospitality,Noida,NaN,Rs 1 crore,Equity Funding,1,Balmer Lawrie & Co Ltd
747,KIBI Sports,Sports Tech,Bengaluru,NaN,"$100,000",Pre-Seed Funding,4,"Angel Investors including Saurabh Aggarwal, Ar..."

In [210]:
df2 = pd.read_csv(r"C:\Users\kevin\yourstory_startups_merged.csv")
df2

,name,sectors,headquarters,funding,employee_count
0,VTC-India,Direct-To-Consumer Brands,Jamnagar,$500,41 to 60
1,A New India,"Software, Technology, Services",New Delhi,$1.0k,41 to 60
2,Topdeck India Tour Booking Pvt Ltd,"Consumer, Travel/Hospitality",Jaipur,$1.1k,<10
3,Packers And Movers India,Services,Vadodara,$2.0k,<10
4,India Self News,"Media, Social Media",Sidhi,$10.0k,<10
...,...,...,...,...,...
301,Flora India,"Consumer, Services",New Delhi,-,<10
302,Astra Indo Pharma India,"FMCG, HealthTech / MedTech / Healthcare",Delhi,-,11 to 20
303,MBC BACCHAWALA INDIA,Clothing & Apparel,New Delhi,-,<10
304,IndianteQ,"E-Commerce, Software, Social Media, EdTech/Edu...",Patna,-,<10
305,ZOONIS INDIA,"Consumer, E-Commerce, Software, Consumer Elect...",New Delhi,-,11 to 20

In [211]:
df3 = pd.read_csv(r"C:\Users\kevin\Downloads\Startups1.csv")
df3

,Unnamed: 0,Company,City,Starting Year,Founders,Industries,Description,No. of Employees,Funding Amount in $,Funding Round,No. of Investors
0,0,Urban Company,Gurgaon,2014,"Abhiraj Singh Bhal, Raghav Chandra, Varun Khaitan","Apps, Home Services, Marketplace, Service Indu...",Urban is a marketplace for independent contrac...,1001-5000,445920356,12,16
1,1,Classplus,Noida,2018,"Bhaswat Agarwal, Bikash Dash, Mukul Rustagi, N...","B2B, E-Learning, EdTech, Education, Mobile App...",Classplus is a mobile-first SaaS platform that...,101-250,89506451,10,20
2,2,Paytm,Noida,2010,"Akshay Khanna, Vijay Shekhar Sharma","E-Commerce, Finance, Financial Services, Inter...",Paytm is a payment gateway that allows users a...,501-1000,32448851,4,4
3,3,Apna,Mumbai,2019,Nirmit Parikh,"Employment, Human Resources, Recruiting, Staff...",Apna is a professional networking and job-sear...,101-250,93450000,4,6
4,4,Razorpay,Bengaluru,2014,"Harshil Mathur, Shashank Kumar","Financial Services, FinTech, Payments, Software","Razorpay is a payment acceptance, processing, ...",1001-5000,366600000,7,29
...,...,...,...,...,...,...,...,...,...,...,...
295,295,SafexPay,Thane,2017,Ravi Gupta,"FinTech, Payments",Safexpay is a B2B2B finance company that speci...,51-100,5280000,1,2
296,296,Pariksha,Pune,2015,"Deepak Choudhary, Karanvir Singh Shekhawat, Ut...","E-Learning, EdTech, Education, Skill Assessment",Pariksha - The Success App is India's leading ...,51-100,6065079,7,20
297,297,Fyllo,Bengaluru,2019,"Sachin Gautam, Sudhanshu Rai, Sumit Sheoran","Agriculture, AgTech, Artificial Intelligence, ...",Fyllo is a precision agriculture service provi...,11-50,557033,4,6
298,298,CredFlow,New Delhi,2019,Kunal Aggarwal,"Credit, Financial Services",CredFlow offers financial services that help y...,1-10,1824000,1,4
299,299,HalaPlay Technologies,Bengaluru,2016,Swapnil Saurav,"Digital Entertainment, Fantasy Sports, Sports",HalaPlay Technologies is a platform for daily ...,1-10,7964767,3,8

In [212]:
df1.columns

Index(['name', 'sector', 'city', 'state', 'funding_total', 'funding_round',
       'number_of_investors', 'investors'],
      dtype='object')

In [213]:
df2.columns

Index(['name', 'sectors', 'headquarters', 'funding', 'employee_count'], dtype='object')

In [214]:
df3.columns

Index(['Unnamed: 0', 'Company', 'City', 'Starting Year', 'Founders',
       'Industries', 'Description', 'No. of Employees', 'Funding Amount in $',
       'Funding Round', 'No. of Investors'],
      dtype='object')

In [215]:
df4 = pd.read_csv(r"C:\Users\kevin\Downloads\startup_cleaned.csv")
df4

,date,startup,vertical,subvertical,city,investors,round,amount
0,2020-09-01,BYJUâ€™S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,1650.000000
1,2020-01-13,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,66.399250
2,2020-09-01,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,151.460595
3,2020-02-01,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,24.750000
4,2020-02-01,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,14.850000
...,...,...,...,...,...,...,...,...
2817,2015-04-29,Tracxn,Startup Analytics platform,NaN,Bangalore,SAIF Partners,Private Equity,28.875000
2818,2015-04-29,Dazo,Mobile Food Ordering app,NaN,Bangalore,"Sumit Jain, Aprameya Radhakrishna, Alok Goel, ...",Seed Funding,0.000000
2819,2015-04-29,Tradelab,Financial Markets Software,NaN,Bangalore,Rainmatter,Seed Funding,3.300000
2820,2015-04-29,PiQube,Hiring Analytics platform,NaN,Chennai,The HR Fund,Seed Funding,4.125000
2821,2015-04-29,Travel Triangle,Online Travel Marketplace,NaN,Noida,"Bessemer Venture Partners, SAIF Partners",Private Equity,66.000000

In [216]:
df4.columns

Index(['date', 'startup', 'vertical', 'subvertical', 'city', 'investors',
       'round', 'amount'],
      dtype='object')

In [217]:
df1.rename(columns={
    'name': 'company_name',
}, inplace=True)

df2.rename(columns={
    'name': 'company_name',
    'sectors': 'sector',
    'headquarters': 'city',
    'funding': 'funding_total'
}, inplace=True)

df3.rename(columns={
    'Company': 'company_name',
    'City': 'city',
    'Industries': 'sector',
    'No. of Employees': 'employee_count',
    'Funding Amount in $': 'funding_total',
    'Funding Round': 'funding_round',
    'No. of Investors': 'number_of_investors'
}, inplace=True)

df4.rename(columns={
    'startup': 'company_name',
    'vertical': 'sector',
    'round': 'funding_round',
    'amount': 'funding_total'
}, inplace=True)

In [218]:
df4['sector'] = df4['sector'].fillna('')
df4['subvertical'] = df4['subvertical'].fillna('')
df4['sector'] = df4.apply(
    lambda row: f"{row['sector']} - {row['subvertical']}" if row['subvertical'] else row['sector'],
    axis=1
)
df4.drop(columns=['subvertical'], inplace=True)

In [219]:
for df in [df1, df2, df3, df4]:
    df['company_name'] = df['company_name'].str.strip().str.lower()

In [220]:
common_columns = [
    'company_name', 'sector', 'city', 'state', 'funding_total', 'funding_round',
    'number_of_investors', 'investors', 'employee_count', 'Unnamed: 0',
    'Starting Year', 'Founders', 'Description', 'date'
]

for df in [df1, df2, df3, df4]:
    for col in common_columns:
        if col not in df.columns:
            df[col] = None

In [221]:
combined_df = pd.concat([df1, df2, df3, df4], ignore_index=True)

# Drop duplicates based on both company_name and location
deduped_df = combined_df.drop_duplicates(subset=['company_name', 'city'], keep='first')

In [222]:
deduped_df.to_csv('STARTUPDATA.csv', index=False)

In [223]:
df = pd.read_csv('STARTUPDATA.csv')

In [224]:
df.head()

,company_name,sector,city,state,funding_total,funding_round,number_of_investors,investors,employee_count,Unnamed: 0,Starting Year,Founders,Description,date
0,art of time,Consumer Goods > Retailers,Maharashtra,NaN,Undisclosed,Series B,1.0,Plutus Wealth Management,NaN,NaN,NaN,NaN,NaN,NaN
1,sammaan capital,Financial Services > Consumer and SME Loans,Delhi,NaN,$1B,Post IPO,2.0,"IHC, Marshall Wace",NaN,NaN,NaN,NaN,NaN,NaN
2,freight tiger,Consumer > Logistics Tech,Maharashtra,NaN,$13.5M,Series C,2.0,"Tata Motors, Lightspeed India",NaN,NaN,NaN,NaN,NaN,NaN
3,recyclaro.com,Environment Tech > Solid Waste Management Tech,Uttar Pradesh,NaN,$1M,Seed,1.0,CapitalOven,NaN,NaN,NaN,NaN,NaN,NaN
4,growxcd,Financial Services > Consumer and SME Loans,Tamil Nadu,NaN,$22.5M,Series B,2.0,"Blue Earth Capital, Lok Capital",NaN,NaN,NaN,NaN,NaN,NaN

In [225]:
# Ensure both columns exist and are treated as strings
df['Starting Year'] = df['Starting Year'].astype(str).str.strip()
df['date'] = df['date'].astype(str).str.strip()

# Replace empty strings or 'nan' with None
df['Starting Year'] = df['Starting Year'].replace(['', 'nan', 'NaN'], None)
df['date'] = df['date'].replace(['', 'nan', 'NaN'], None)

# Combine into a new column
df['startup_date'] = df.apply(
    lambda row: row['Starting Year'] if row['Starting Year'] else row['date'],
    axis=1
)

In [226]:
# Optional: drop the original columns
df.drop(columns=['Starting Year', 'date'], inplace=True)

In [227]:
manual_dates = {'art of time': '2000', 'sammaan capital': '2005', 'freight tiger': '2014', 'recyclaro.com': '2025', 'growxcd': '2022', 'unmannd': '2025', 'vamam': '2000', 'climaty ai': '2024', 'ignosis': '2022', 'fyno': '2022', 'recur club': '2021', 'wit and chai group': '2020', 'hocco': '2019', 'petpoojam': '2011', 'kapivas': '2015', 'vaani research labs': '2024', 'ef polymer': '2018', 'rugr': '2022', 'igowise': '2020', 'pharmeasy': '2015', 'emergent': '2024', 'chakr innovation': '2016', 'curefoods': '2020', 'handpickd': '2024', 'rocket': '1963', 'vedantu': '2014', 'simple energy': '2019', 'kisankonnect': '2020', 'distil': '2023', 'gullak': '2022', 'oolka': '2024', 'prism': '2013', 'onfinance': '2023', 'amwoodo': '2019', 'cosmoserve space': '2025', 'p-tal': '2017', 'xbattery': '2024', 'vyomic': '2024', 'akashalabdhi': '2023', 'navo': '2025', 'bharat intelligence': '2024', 'recove': '2024', 'paar autonomy': '2024', 'samaaro': '2015', 'gaadimech': '2020', 'gabit': '2022', 'infra.market': '2016', 'evoluteiq': '2019', 'finbox': '2015', 'blue energy motors': '2020', 'incred money': '2015', 'ecosoul': '2021', 'indkal': '2018', 'scalekit': '2023', 'lucira': '2025', 'spacefields': '2021', 'pelocal fintech': '2021', 'ido devices': '2025', 'pascal ai labs': '2024', 'equilibrium': '2011', 'includ': '2023', 'blinkit-ai': '2024', 'supply6': '2019', 'ugx.ai': '2023', 'playsuper': '2024', 'wankel energy systems': '2022', 'mynaksh': '2025', 'uknowva': '2012', 'raptee.hv': '2018', 'flipspaces': '2011', 'indrajaal': '2023', 'presolv360': '2017', 'indigrid technology': '2016', 'ember': '2000', 'asaya': '2021', 'inamo': '2024', 'wehouse': '2017', 'endureair systems': '2018', 'snap-e-cabs': '2022', 'aurva': '2023', 'bacalt biosciences': '2023', 'peakamp': '2024', 'farmdidi': '2021', 'prowrrap': '2024', 'biokraft foods': '2023', 'misfits': '1977', 'traqcheck': '2020', 'citymall': '2019', 'seekho': '2020', 'blue tokai coffee roasters': '2013', 'firstclub': '2024', 'colive': '2016', 'offgrid energy': '2018', 'reveal healthtech': '2023', 'platinumrx': '2023', 'leafybus': '2023', 'tuco kids': '2023', 'flexifyme': '2021', 'autodukan': '2017', 'house of zelena': '2021', 'cuzor': '2019', 'rxmen': '2023', 'quante energy': '2024', 'dectrocel': '2020', 'waterscience': '2014', 'edgehax': '2025', 'transbnk': '2022', 'altum credo': '2016', 'credright': '2016', 'wizcommerce': '2020', 'vutto': '2024', 'palmonas': '2022', 'enmovil': '2015', 'peeko': '2025', 'matiks': '2024', 'wastelink': '2018', 'harajuku tokyo cafe': '2021', 'cumin co': '2024', 'anmasa': '2024', 'nugen': '2009', 'vaave': '2013', 'hexafun': '2021', 'nuyug': '2024', 'bhaobhao': '2025', 'r for rabbit': '2014', 'kiwi': '2022', 'beyond appliances': '2024', 'house of biryani': '2022', 'mitra': '2022', 'peelon': '2020', 'famyo': '2023', 'zenzebra': '2024', 'truemeds': '2019', 'zepto': '2021', 'darwinbox': '2015', 'ultraviolette': '2016', 'arintra': '2020', 'dashverse': '2023', 'lifelong online': '2015', 'pronto': '2024', 'elivaas': '2023', 'graas.ai': '2022', 'refold ai': '2022', 'olee space': '2019', 'holiday tribe': '2022', 'fairdeal.market': '2022', 'manastu space technologies': '2017', 'comminent': '2018', 'spike ai': '2024', 'trackk': '2021', 'the sleep company': '2019', 'renee cosmetics': '2018', 'fibe': '2015', 'supergaming': '2017', 'jeh aerospace': '2022', 'zype': '2022', 'turbohire': '2019', 'mitigata': '2021', 'tplusa india': '2024', 'cautio': '2023', 'outzidr': '2024', 'hylenr': '2024', 'codekarma': '2024', 'xovian aerospace': '2018', 'nuuk': '1728', 'designx': '2015', 'eon space labs': '2021', 'mangopoint': '2018', 'fraganote': '2022', 'shotgun games': '2021', 'gladful': '2021', 'terafac': '2021', 'prozo': '2014', 'safe security': '2012', 'metaforms': '2019', 'stan': '2015', 'arivihan': '2019', 'sharpsell.ai': '2022', 'drizz': '2024', 'littlebox': '2022', 'snooplay': '2019', 'heizen': '2024', 'passport trips': '2023', 'iline': '2024', 'genexis biotech': '2019', 'vahan.ai': '2016', 'gupshup': '2004', 'netrasemi': '2020', 'superk': '2019', 'kluisz.ai': '2025', 'edufund': '2020', 'eveez': '2019', 'enlite research': '2017', 'ituring.ai': '2018', 'sugar cosmetics': '2012', 'escape plan': '2025', 'hudle': '2015', 'grexa ai': '2024', 'anny': '2023', 'ammunic systems': '2024', 'inbound aerospace': '2025', 'plenome technologies': '2023', 'bharatsure': '2021', 'apclub': '2023', 'coluxe': '2025', 'magma': '2007', 'roast foods': '2017', 'klugklug': '2022', 'qpiai': '2019', 'phi commerce': '2015', 'knot': '2022', 'trupeer.ai': '2023', 'omspace rocket & exploration': '2020', 'vaaree': '2022', 'curefit': '2016', 'dcg tech': '2005', 'zuppa': '2008', 'deep algorithm': '2021', 'dial4242': '2016', 'the wedding company': '2023', 'navana.ai': '2018', 'unibose': '2016', 'zulu club': '1916', 'parkobot': '2023', 'enercomp': '2013', 'cosmoss': '2024', 'onetab.ai': '2023', 'fire ai': '2024', 'infinity fincorp': '2016', 'varthana': '2013', 'khetika': '2017', 'inprime finserv': '2021', 'chai bisket': '2015', 'belong': '2014', 'clean fanatics': '2010', 'cookd': '2020', 'gramik': '2021', 'green aero': '2023', 'wiselife': '2020', 'linkrunner': '2024', 'divine hindu': '2023', 'ldotr': '2024', 'qoruz': '2015', 'jumbotail': '2015', 'incred finance': '2016', 'eggoz': '2017', 'appsforbharat': '2020', 'aukera': '2023', 'bambrew': '2018', 'eeki': '2018', 'zango ai': '2024', 'maieutic semiconductor': '2025', 'luma fertility': '2024', 'gobblecube': '2022', 'loopworm': '2019', 'cimware': '2018', 'sthyr energy': '2024', 'astrophel aerospace': '2021', 'lamark biotech': '2018', 'fitfeast': '2021', 'garaaz': '2019', 'fes cafe': '2019', 'ajnalens': '2014', 'raphe mphibr': '2017', 'giva': '2019', 'eka mobility': '2019', 'shopos': '2024', 'gokwik': '2020', 'sahi': '2023', 'fabheads': '2015', 'kazam': '2020', 'stayvista': '2015', 'rabitat': '2019', 'zilo': '2025', 'evera cabs': '2019', 'coratia technologies': '2021', 'fantail': '2023', 'armory': '1994', 'jobizo': '2020', 'skippi': '2020', 'auraml': '2023', 'innovodigm': '2020', 'truliv': '2019', 'wiom': '2015', 'oben electric': '2020', 'techfino': '2018', 'saswat finance': '2022', 'illumine': '2018', 'darwix ai': '2021', '7 ring': '2018', 'nuvie': '2024', 'xportel': '2024', 'decentro': '2020', 'sanlayan technologies': '2023', 'roomstory.ai': '2024', 'vecmocon technologies': '2016', 'cred': '2018', 'flick tv': '2025', 'wow! momo': '2008', 'powerup money': '2024', 'flexiloans': '2016', 'garuda aerospace': '2015', 'piston': '2024', 'leumas': '2016', 'machaxi': '2019', 'repello': 'AI', 'kisah': '2018', 'iom bioworks': '2022', 'plutope': '2022', 'spinny': '2015', 'qubeats': '2023', 'nxt meal': '2020', 'the tarzan way': '2020', 'loantap': '2016', 'plush': '2019', 'naagin sauce': '2019', 'khari foods': '2022', 'stride green': '2024', 'gully labs': '2023', 'manipal group': '1993', 'gyandhan': '2015', 'shapoorji pallonji': '1865', 'udaan': '2016', 'pepperfry': '2011', 'spense': '2022', 'samunnati': '2014', 'farmako': '2019', 'snitch': '2019', 'stable money': '2022', 'biopeak': '2024', 'kosmc ai': '2024', 'atlanture sports': '2020', 'true diamond': '2024', 'upurfit': '2023', 'euler motors': '2018', 'cloudsek': '2015', 'curebay': '2021', 'miraggio': '2005', 'tan90': '2019', 'mythik': '2023', 'biostate ai': '2023', 'data sutram': '2018', 'zoca': '2023', 'promethean energy': '2021', 'shuru': '2024', 'alt carbon': '2021', 'blackcarrot': '2024', 'openfx': '2022', 'kskt': '2023', 'farmley': '2017', 'avammune therapeutics': '2023', 'celebal tech': '2016', 'citrus freight': '2016', 'm1xchange': '2017', 'hyperbots': '2023', 'biryani blues': '2013', 'be clinical': '2024', 'jsw one': '2022', 'tiea connectors': '2020', 'flam': '2021', 'adopt ai': '2024', 'reelsaga': '2024', 'bluestone': '2011', 'vflowtech': '2018', 'contravault ai': '2024', 'third bracket': '2022', 'luzo': '2021', 'complement1': '2024', 'naptapgo': '2023', 'medvital': '2023', '1-india family mart': '2012', 'zenergize': '2024', 'nobel hygiene': '1999', 'fyn mobility': '2013', 'volt14': '2018', 'store my goods': '2021', 'alt drx': '2021', 'lifechart': '2021', 'celcius logistics': '2020', '91trucks': '2022', 'troovy': '2021', 'nawgati': '2019', 'korinmi': '2024', 'the good bug': '2021', 'inspecity': '2022', 'insurance samadhan': '2018', 'routematic': '2013', 'shiplog': '2020', 'blissclub': '2019', 'posha': '2017', 'pb healthcare': '2025', 'vaya finserv': '2014', 'high time foods': '2022', 'zebu': '2017', 'feline spirits': '2019', 'gotrust': '2016', 'footprints preschool & daycare': '2012', 'porter': '2014', 'uni seoul': '2023', 'malaki': '2018', 'care.fi': '2021', 'metafin': '2018', 'mugafi': '2020', 'collegedekho': '2015', 'primebook': '2018', 'scandalous foods': '2020', 'kult': '2019', 'qnu': '2016', 'vividobots': '2021', 'hexahealth': '2021', 'satleo labs': '2023', 'sadhav offshore': '1992', 'anveshan': '2019', 'salt oral care': '2023', 'ivana jewels': '2023', 'kaleidofin': '2017', 'finodaya capital': '2024', 'ivory': '1997', 'matbook': '2023', 'rebel foods': '2011', 'devassure': '2024', 'poshs metal': '1998', 'mydesignation': '2017', 'emversity': '2023', 'vayudh': '2016', 'bankbazaar': '2008', 'savein': '2020', 'intellicar': '2015', 'greengrahi': '2021', 'rimigo': '2024', 'optimized electrotech': '2017', 'v safe': '2020', 'sportsskill': '2021', 'jupiter international': '1978', 'cura care': '2025', 'noto': '2019', 'beastlife': '2024', 'centa': '2014', 'jewelbox': '2022', 'rio innobev': '2014', 'ofbusiness': '2015', 'nothing before coffee': '2017', 'peppermint robotics': '2019', 'ipec': '2013', 'jetsynthesys': '2012', 'easebuzz': '2014', 'asha ventures': '2014', 'vimano': '2019', 'innovist': '2018', 'calligotech': '2012', 'juspay': '2012', 'sadbhav future tech': '2024', 'siglq.ai': '2024', 'daveai': '2018', 'agrostar': '2012', 'eat better': '2017', 'amicco': '2024', "let's try": '2021', 'parÃ© innovations': '2020', 'bhagva': '2022', 'noise': '2014', 'xindus': '2022', 'eloelo': '2020', 'askmyguru': '2025', 'bower': '2012', 'mosaic wellness': '2019', 'greenline mobility solutions': '2021', 'koparo': '2020', 'lehlah': '2022', 'tvaster genkalp': '2021', 'evenflow': '2021', 'wendor': '2017', 'stance health': '2024', 'the bear house': '2017', 'decharge': '2024', 'yatrikart': '2021', 'argos watches': '2022', 'better nutrition': '2023', 'innergize': '2023', 'fur jaden': '2015', 'flipkart internet': '2011', 'pratilipi': '2014', 'rapidclaims': '2023', 'furtherai': '2023', 'sweet karam coffee': '2015', 'scapia': '2022', 'perkant tech': '2020', 'drivershaab': '2019', 'tonbo imaging': '2008', 'aerem solutions private limited': '2018', 'alienkind': '2024', 'nexthop ai': '2024', 'abound': '2020', 'smallcase': '2015', 'country delight': '2015', 'apna mart': '2021', 'dcdc kidney care': '2009', 'shoegr': '2021', 'otipy': '2020', 'slikk club': '2024', 'protectt.ai': '2020', 'nivara home finance': '2014', 'pilgrim': '2025', 'chai kings': '2016', 'qila games': '2024', 'lighthouse proptech': '2023', 'iyaso': '2023', 'my pahadi dukan': '2021', 'navadhan': '2019', 'asper.ai': '2022', 'everhope oncology': '2025', 'harvested robotics': '2023', 'nourish you': '2015', 'ihub robotics': '2021', 'hypergro.ai': '2022', 'gooat': '2023', 'go zero': '2022', 'yummy bee': '2022', 'zolve': '2020', 'scimplify': '2023', 'purple style labs': '2015', 'amperehour energy': '2017', 'gostops': '2014', 'indÄ“ wild': '2021', 'swish': '2024', 'gainhub.ai': '2022', 'mapmycrop': '2021', 'maxiq (formerly gyaan ai)': '2022', 'phot.ai': '2022', 'insurancedekho': '2016', 'beacon.li': '2023', 'geniemode': '2021', 'bridgetown': 'Research', 'oxyzo': '2016', 'quick': 'Clean', 'dr. reddyâ€™s laboratories': '1984', 'fantv': '2019', 'vidyut': '2021', 'technodysis': '2015', 'sisir': 'Radar', 'astrogate labs': '2019', 'triple tap games': '2024', 'dodo payments': '2024', 'ritualistic': '2018', 'earthful': '2020', 'pickkup': '2018', 'make in box': '2020', 'lightstorm': '2018', 'waterfield advisors': '2011', 'spyne': '2018', 'the whole truth': '2019', 'singulr ai': '2023', 'dogsee chew': '2015', 'rare rabbit': '2015', 'ikonz studios': '2021', 'probus smart things': '2017', 'swish club': '2023', 'onetab ai': '2023', 'almonds ai': '2017', 'noto ice cream': '2019', 'dynolt technologies': '2022', 'you care lifestyle': '2020', 'healthfab': '2019', 'bytes': '2022', 'encharge ai': '2022', 'tonetag': '2013', 'spotdraft': '2017', 'zeta': '2015', '75f': '2012', 'rapido': '2015', 'jqr': '2011', 'lucidity': '2021', 'nirmata': '2013', 'borderplus': '2025', 'bold care': '2019', 'capgrid solutions': '2019', 'nivaan care': '2023', 'toonsutra': '2022', 'mysa': '2023', 'eduvanz': '2016', 'arthalpha': '2023', 'anscer robotics': '2020', 'the energy company': '2021', 'future agi': '2024', 'cogniquest': '2022', 'raincheck earth co.': '2022', 'rupeeflo': '2024', 'gorally': '2024', 'stepout': '2020', 'legup': '2015', 'croft beverages': '2021', 'myntra': '2007', 'captain fresh': '2019', 'truefoundry': '2021', 'cognida.ai': '2022', 'hair originals': '2018', 'nua': '2017', 'scentials': '2017', 'dreamfly innovations': '2019', 'mealawe': '2024', 'fitspire': '2020', 'quicklend': '2024', 'babynama': '2022', 'presage insights': '2024', 'origamis ai': '2022', 'astra security': '2016', 'bonv aero': '2023', 'meesho': '2015', 'leap': '2019', 'atomicwork': '2022', 'superops': '2020', 'innov8': '2015', 'geri care health services': '2018', 'emiza': '2015', 'voltup': '2019', 'astrome technologies': '2015', 'ambak': '2023', 'growxcd finance': '2022', 'whizzo': '2024', 'bizloan': '2016', 'salad days': '2013', 'chk': '2024', 'metashot': '2021', 'sammmm': '2024', 'origin fresh': '2020', 'shoppin': '2023', 'thinkmetal': '2021', 'utsav': '2021', 'medmitra ai': '2023', 'dressfolk': '2015', 'nazara technologies': '1999', 'ati motors': '2017', 'aris infra solutions': '2021', 'deconstruct': '2020', 'vunet systems': '2014', 'medusa beverages': '2017', 'snabbit': '2024', 'landeed': '2022', 'bpr hub': '2024', 'pipeshift': '2024', 'zeelab pharmacy': '2019', 'procureyard': '2023', 'workie': '2017', 'cancrie': '2020', 'raaz app': '2024', 'postudio': '2020', 'chelvies coffee': '2023', 'krvvy': '2023', 'prantae solutions': '2015', 'exsure': '2021', 'dream aerospace': '2022', 'svastek': '2020', 'joyspoon': '2022', 'aragen': '2001', 'netradyne': '2015', 'wework india': '2017', 'foxtale': '2021', 'ecozen': '2010', 'bgauss': '2020', 'micromitti': '2023', 'sarla aviation': '2023', 'skor technologies': '2023', 'astrosure.ai': '2024', 'emiza supply chain services': '2015', 'eccentric': '2012', 'wevois': '2018', 'boba bhai': '2023', 'constelli': '2017', 'fambo': '2022', 'tyreplex': '2020', 'zerocircle': '2020', 'kisaansay': '2023', 'erlysign': '2019', 'orbitaid': '2021', 'greenstitch': '2023', 'parkmate': '2021', 'reput.ai': '2024', 'quash': '2023', 'house of chikankari': '2020', 'tractor factory': '2022', 'sukoon unlimited': '2024', 'indiyanet': '2023', 'innovaccer inc.': '2012', 'oyo': '2012', 'infinity fincorp solutions': '2016', 'botanic healthcare': '2013', 'waycool': '2015', 'grayquest': '2017', 'vehant technologies': '2005', 'mintoak': '2017', 'beyond snack': '2018', 'emo energy': '2022', 'ras': '2017', 'rasa (conversational ai platform)': '2020', 'brainsight ai': '2019', 'hbits': '2022', 'zoplar': '2024', 'consint.ai': '2024', 'kibi sports': '2024'}

    


df['startup_date'] = df['company_name'].map(manual_dates).fillna(df['startup_date'])

In [228]:
df.isna().sum()

company_name              0
sector                    1
city                      0
state                  3553
funding_total             0
funding_round           306
number_of_investors    2548
investors               604
employee_count         2962
Unnamed: 0             3268
Founders               3268
Description            3268
startup_date            326
dtype: int64

In [229]:
df.head(5)

,company_name,sector,city,state,funding_total,funding_round,number_of_investors,investors,employee_count,Unnamed: 0,Founders,Description,startup_date
0,art of time,Consumer Goods > Retailers,Maharashtra,NaN,Undisclosed,Series B,1.0,Plutus Wealth Management,NaN,NaN,NaN,NaN,2000
1,sammaan capital,Financial Services > Consumer and SME Loans,Delhi,NaN,$1B,Post IPO,2.0,"IHC, Marshall Wace",NaN,NaN,NaN,NaN,2005
2,freight tiger,Consumer > Logistics Tech,Maharashtra,NaN,$13.5M,Series C,2.0,"Tata Motors, Lightspeed India",NaN,NaN,NaN,NaN,2014
3,recyclaro.com,Environment Tech > Solid Waste Management Tech,Uttar Pradesh,NaN,$1M,Seed,1.0,CapitalOven,NaN,NaN,NaN,NaN,2025
4,growxcd,Financial Services > Consumer and SME Loans,Tamil Nadu,NaN,$22.5M,Series B,2.0,"Blue Earth Capital, Lok Capital",NaN,NaN,NaN,NaN,2022

In [230]:
manual_dates = { 'grest':'2018',
'pelocal fintech':'2021',
'zanskar':'2023',
'amama':'2018',
'pop':'2023',
'knest':'2014',
'repello ai':'2023',
'vaya':'2014',
'stimuler':'2022',
'fuze':'2006',
'greenline mobility solutions ltd.':'2021',
'broadway':'2001',
'bridgetown research':'2023',
'quick clean':'2009',
'hiwipay':'2022',
'sisir radar':'2021',
'hair originals':'2018',
'fleksa':'2017',
'india hemp and co':'2020',
'instantpay':'2013',
'bolo indya':'2019',
'electrik mobility india':'2020',
'shadani india private limited':'2007',
'sparsh foods':'2005',
'fossil':'2012',
'btw visa services':'2011',
'truly earthy':'2015',
'surbhi gajak':'1961',
'strike':'2015',
'sundae':'2018',
'shikhar travels':'1979',
'shree tripada':'2011',
'verts services india':'2006',
'skandhanshi infra projects':'2009',
'yatrirestro':'2019',
'pickle gallery':'2007',
'wdipl (website developers india)':'2001',
'crazy d':'2021',
'splendid facility management':'2009',
'nayaha':'2021',
'paninian':'2018',
'resource engimech':'2005',
'vinterview ai':'2017',
'scottish high international school':'2004',
'spine technologies':'2018',
'the colourmoon technologies':'2019',
'giva jewellery':'2019',
'vikalp india':'2023',
'origo commodities india pvt. ltd':'2010',
'gradatim':'2006',
'rudra environmental solution':'2012',
'godi':'2020',
'tech divinity':'2020',
'ug4 india':'2023',
'payme india':'2015',
'future choice hospitality':'2014',
'continual engine':'2010',
'mapmygenome':'2013',
'eduncle':'2014',
'ok india':'2024',
'saathi':'2015',
'wlc':'1996',
'new india construction':'2010',
'gadget rental india':'2017',
'oem india':'2004',
'crayon box india':'2021',
'atlas technologies civil and road construction machinery manufacturer in india':'2022',
'mind frame india':'2016',
'red rock india':'2015',
'carhp india':'2018',
'brandweb india':'2019',
'astroscience technologies india private limited':'2018',
"student ai - india's first ai powered usb for students":'2024',
'elder first - senior living':'2021',
'spa hibiscus india':'2008',
'zealand immigration india private limited':'2023',
'iae global india':'2015',
'value findr india':'2016',
'effective lab india':'2015',
'whitewolf india':'2023',
'ritvi steel buildings india private limited':'2019',
'emerging india analytics':'2017',
'peddler media network india':'2017',
'aula india':'2024',
'south indian jewels':'2020',
'dormen india':'2001',
'seo company india- aarinfotech':'2012',
'chalbo india':'2018',
'buy books india':'2009',
'coin developer india':'2023',
'the west indian honey co.':'2023',
'london institute of banking & finance india':'2012',
'global india business forum':'2017',
'opsis consulting india':'2014',
'navision india':'2002',
'india tours cabs':'2011',
'regulatory solutions india':'2008',
'brds india (bhanwar rathore design studio)':'2005',
'space india':'1999',
'corvids india':'2016',
'indiai':'2024',
'great indian services':'2017',
'deloitte india':'1999',
'ess india (employee services and solutions)':'1997',
'niceway india':'2009',
'nobero india':'2017',
'viacom india':'2007',
'krishna construction india':'2007',
'ceeon india pvt. ltd.':'2018',
'first edu india':'2013',
'whatnot india':'2023',
'indian silk house exclusives':'1926',
'trav my india':'2011',
'india property dekho':'2013',
'veils india':'2024',
'pokonut india':'2021',
'arcpro digital india':'2020',
'zenius india':'2018',
'gi cancer india':'2023',
'indiabizforsale':'2014',
'actax india':'2016',
'giks india':'2009',
'mobi india':'2011',
'the wanderer india':'2020',
'salam mirror india':'2019',
'indiadeposit':'2021',
'sokudo electric india':'2023',
'unitile india':'1996',
'ssat india':'2011',
'sands india':'2008',
'skill talks india':'2020',
'getpage india':'2023',
'cfi - coaching foundation india':'2014',
'one india securities':'2018',
'hire help india':'2015',
'al safa demolition contractors india':'2023',
'everbloom india':'2017',
'raj flavours india':'2023',
'ifragrance india':'2022',
'bongchie india':'2018',
'indianvillez':'2019',
'icrl india':'2012',
'sagami india - japanese logistics':'2013',
'swayam india':'2005',
'evable india':'2023',
'modular concepts india':'2015',
'otu india':'2014',
'softrate india':'2023',
'kenstar india':'1996',
'carton india':'2018',
'handycraft india':'2018',
'ab initio india':'2006',
'india flux':'2021',
'agriplex india':'2019',
'evtl india':'2020',
'taj indian':'2022',
'fuelcab india':'2023',
'biobritte india':'2016',
'india thrills':'2019',
'forest essentials india':'2000',
'mc fox india':'2020',
'suthe e-commerce india':'2022',
'ceeon india':'2014',
'blue ocean academy india':'2022',
'motovil india':'2012',
'vacation trip india':'2008',
'india career centre':'2022',
'online legal india':'2019',
'humanity foundation of india':'2003',
'indian corporate gifts':'2012',
'india tourism':'1966',
'ferosh india':'2016',
'gemeria hair india':'2013',
'prodemy india':'2021',
'forethought india':'2022',
'prymus brandcom india':'2017',
'medimove india':'2020',
'pain free india physiotherapy at home':'2020',
'astra indo pharma india':'2022',
'mbc bacchawala india':'2021',
'indianteq':'2021',
'hair originals':'2018',
'pelocal fintech':'2021',
'dpdzero':'2022',
'moonrider private limited':'2023',
'vtc-india':'2008',
'a new india ':'1919',
'topdeck india tour booking private limited':'2023',
'packers and movers india private limited':'2000',
'deskmate global express india private limited':'2012',
'wealth 4 india private limited':'2013',
'adzenia':'2021',
'global colours and chemicals limited':'2017',
'sunsys technologies india pvt. ltd.':'2006',
'amar food products india':'1984',
'esports daily':'2020',
'cleanly':'2012',
'india internets':'2002',
'best of indian products':'2001',
'wdipl ':'2001',
'older first':'2021',
'ritvi steel buildings india private limited':'2019',
'brds india ':'2005',
'ess india ':'1997',
'assesslim':'2022'

 }


df['startup_date'] = df['company_name'].map(manual_dates).fillna(df['startup_date'])

In [231]:
df

,company_name,sector,city,state,funding_total,funding_round,number_of_investors,investors,employee_count,Unnamed: 0,Founders,Description,startup_date
0,art of time,Consumer Goods > Retailers,Maharashtra,NaN,Undisclosed,Series B,1.0,Plutus Wealth Management,NaN,NaN,NaN,NaN,2000
1,sammaan capital,Financial Services > Consumer and SME Loans,Delhi,NaN,$1B,Post IPO,2.0,"IHC, Marshall Wace",NaN,NaN,NaN,NaN,2005
2,freight tiger,Consumer > Logistics Tech,Maharashtra,NaN,$13.5M,Series C,2.0,"Tata Motors, Lightspeed India",NaN,NaN,NaN,NaN,2014
3,recyclaro.com,Environment Tech > Solid Waste Management Tech,Uttar Pradesh,NaN,$1M,Seed,1.0,CapitalOven,NaN,NaN,NaN,NaN,2025
4,growxcd,Financial Services > Consumer and SME Loans,Tamil Nadu,NaN,$22.5M,Series B,2.0,"Blue Earth Capital, Lok Capital",NaN,NaN,NaN,NaN,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3549,reglobe,Used Gadgets Buy / Refurbishing,Gurgaon,NaN,8.25,Seed Funding,NaN,"Bessemer Ventures, Blume Ventures",NaN,NaN,NaN,NaN,2015-04-29
3550,icertis,Cloud Enterprise Software,Pune / US,NaN,49.5,Private Equity,NaN,"Greycroft Partners, Fidelity Growth Partners",NaN,NaN,NaN,NaN,2015-04-29
3551,dazo,Mobile Food Ordering app,Bangalore,NaN,0.0,Seed Funding,NaN,"Sumit Jain, Aprameya Radhakrishna, Alok Goel, ...",NaN,NaN,NaN,NaN,2015-04-29
3552,tradelab,Financial Markets Software,Bangalore,NaN,3.3,Seed Funding,NaN,Rainmatter,NaN,NaN,NaN,NaN,2015-04-29
3553,piqube,Hiring Analytics platform,Chennai,NaN,4.125,Seed Funding,NaN,The HR Fund,NaN,NaN,NaN,NaN,2015-04-29

In [232]:
df.to_csv("STARTUPDATA.csv", index=False)

In [233]:
df = pd.read_csv("STARTUPDATA.csv")